### ISSUE TITLE
Privacy Day Task; law.mit.edu/OpenConsent - Needs to be updated 

### ISSUE THREAD

**Issue by smartopian** [OpenConsent/openconsentgroup#11]
Need to get the link to the unconference project for privacy day onto this page, with ideally.

 The I Don’t Agree campaign weblink with a note:  Developed in London during the FutureOfCommerce Un-Conference is now in action. 
Assets usable so far
- Link to  the project presentation https://docs.google.com/presentation/d/1a7rVNFULxttnf8xlZKHYKlZw88XuNurqQZCDD50g4bo/edit?usp=sharing 
- Link to the I Dont Agree website - and a notice that this is now in progress (get involved) 
- A link to get involved in the project to go forward and  
- Two Unconference videos - introducing the effort

**Comment by dazzaji** [comment]
Mark - I invite you to write up some HTML you propose for the page so I have something to consider.

**Comment by smartopian** [comment]
ah,, this is the problem, I would have to learn html again.  its been 15 years

**Comment by smartopian** [comment]
Is there an existing link to the hackathon/unconference material?

**Comment by dazzaji** [comment]
You can do it in markdown on a GitHub page (using the .md extension) and it is just as good.   Actually, it is much better, because it is focused on basic content and it only needs sufficient functionality with winks and images and not really a lot of fuss around formatting. Also you can do it right here in the same get hub repository that the project is using. That is invaluable. 

As a "why using GitHub issues is the very best method ever in the whole wide world for project management and getting things done" example that you can feel the goodness of, try this: 

(1) once you have it finished the markdown file, please provide a link in a comment to this issue. 

(2) at that point I can either add it as HTML to the project page on the Drupal web site as is, or iterate the markdown using this very issue thread for your consideration, and upon agreement incorporate the corresponding HTML into the webpage

Github issues support markdown. However, it is recommended that you create a markdown file in the repository and refer to that in this thread because it is not possible to link to individual comments within an issue at this point.  So in this issue thread when there is a question about having specific content go this way or that way it's possible to literally put it between dividing lines within the issue ticket to show examples or to put it within a table with one example on the left and another option on the right or any other way that makes sense to discuss and resolve that snippet of content and therefore to resolve this issue and publish or appropriate page.

(3) when this issue is resolved then all we have to do is close the issue and we have both a record of what happened that we or others can review later to know what happened and also a simple and always up-to-date task list based on filtering only active issues in the project repository.

Many people are used to and perhaps without thinking continue to use email for project management. That with my preferred method for many years and I had not yet found a project management system that was better feeling then direct email from me to others for projects I was in charge of until github issues.  I hope that you have an opportunity to see with this issue item related to a web page that matters to you how very easy, efficient, effective, and significantly better then on the next best option this get hub issues method can be.

**Comment by dazzaji** [comment]
The existing material is in the project roster on the wiki of the event site. The report out video that you did on YouTube is not yet there. There are other materials that you have generated as well and all that should be added to the page you're creating.

**Comment by dazzaji** [comment]
Just realized - this issue is not relevant to the work Caitlin and Didar are doing now and should not be on this ticket service at this time while an active development and project cycle are in process.  When you know what content you prefer describing the global open consent project please just communicate that to me directly and we can close this ticket on this project now.

**Comment by smartopian** [comment]
https://github.com/OpenConsent/PrivacyDay/issues/1
